### ISSUE TITLE
Problems with current sources

### ISSUE THREAD

**Issue by bejean** [mattweber/solr-for-wordpress#9]
The plugins doesn't work anymore.
I had to comment 2 lines in solr-options-page.php file

foreach( $options as $key => $value ) {
    if( $existing = get_option($key)) {
      //krumo( $existing);
        $options[$key] = $existing;
        delete_option($key);
        $indexall = FALSE;
          //$option_function($key);
    }
}

Furthermore, it looks like settings are sometimes reset to default (I am investigating)

**Comment by bejean** [comment]
In options page, custom fields options and Exclude posts or page option are always empty.

**Comment by shaksi** [comment]
Have removed debug code and options fields for exclude and custom fields are back in!!

**Comment by shaksi** [comment]
Can you please confirm the above issues are solved with the latest commits

**Comment by bejean** [comment]
Change settings in "Index custom fields", "Excludes Posts or Pages" or "Custom fields as Facet"
Save changes will display the options page with these 3 settings empty
Click on "Solr options" on the left, will display the settings with correct values for these 3 settings

**Comment by shaksi** [comment]
i unable to repeat the above bug/outcome :/

This is with the latest commits?

(this comment & close button is far too close to Comment)

**Comment by bejean** [comment]
yes. I will recheck this.

**Comment by bejean** [comment]
I still have the issue.
In fact, at save time, these 3 options are simple strings "value1,value2, ..." instead to be arrays of string ["value1", "value2", ...]

So, s4w_filter_list2str function return ""

function s4w_filter_list2str($input) {
    if (!is_array($input)) {
        return "";
    }

**Comment by bejean** [comment]
Hi Shaksi !

Are you working on this issue ?

**Comment by shaksi** [comment]
sorry about the lack off update, I am on this and should have something out later tonight.

**Comment by shaksi** [comment]
please confirm this solves the issue, so I can close this.
cheers.

**Comment by bejean** [comment]
Works fine !

Thank you
